CONFIG_LOG=y
CONFIG_NRFX_SAADC=y

# this allows peripherals to interact without cpu intervention 
CONFIG_NRFX_GPPI=y

CONFIG_NRFX_TIMER=y

#enable bluetooth
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_ZEPHYR_NUS=y
 
 #name central device will see when scanning
CONFIG_BT_DEVICE_NAME="grompack"
#allow update to 2M PHY
CONFIG_BT_USER_PHY_UPDATE=y 
#allow DLE
CONFIG_BT_USER_DATA_LEN_UPDATE=y
CONFIG_BT_L2CAP_TX_MTU=247
CONFIG_BT_BUF_ACL_RX_SIZE=251
CONFIG_BT_BUF_ACL_TX_SIZE=251
 #larger buffers
CONFIG_HEAP_MEM_POOL_SIZE=2048
#min connection interval (6*1.25ms = 7.5ms)
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
#max
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12
#slave latency
CONFIG_BT_PERIPHERAL_PREF_LATENCY=0
#supervision timeout (400*10ms = 4s)
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400